**Generating Random numbers with numpy**

https://chrisalbon.com/python/basics/generating_random_numbers_with_numpy/

**Preliminaries**

In [1]:
import numpy as np

**Generate a random number from the normal distribution**

In [2]:
np.random.normal()

0.2931717268436579

**Generate four random numbers from the normal distribution**

In [3]:
np.random.normal(size=4)

array([-0.15033349, -0.13938503, -0.93414434,  1.26867101])

**Generate four random numbers from the uniform distribution**

In [4]:
np.random.uniform(size=4)

array([ 0.32410208,  0.03771389,  0.32199318,  0.14110141])

**Generate four random integers between 1 and 100**

In [6]:
np.random.randint(low=1,high=100,size=4)

array([15, 89, 97, 93])