**Indexing and Slicing NumPy array - Part 2**

**Preliminaries**

In [1]:
import numpy as np

In [3]:
#Create a 2x2 array

battle_deaths = [[344, 2345],[253, 4345]]
deaths = np.array(battle_deaths)
deaths

array([[ 344, 2345],
       [ 253, 4345]])

In [4]:
#Select the top row, second item

deaths[0,1]

2345

In [5]:
#Select the second column

deaths[:,1]

array([2345, 4345])

In [6]:
#Select the second row

deaths[1,:]

array([ 253, 4345])

In [7]:
#Create an array of civilian deaths

civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
civilian_deaths

array([4352,  233, 3245,  256, 2394])

In [8]:
#Find the index of battles with less than 500 deaths
less_deaths = np.where(civilian_deaths < 500)
less_deaths

(array([1, 3]),)

In [9]:
civ_deaths = civilian_deaths[less_deaths]
civ_deaths

array([233, 256])