**Numpy Array Basics**

https://chrisalbon.com/python/basics/numpy_array_basics/

In [2]:
#import modules
import numpy as np

In [3]:
#Create a list

battle_deaths = [3246, 326, 2754, 2547, 2457, 3456]
battle_deaths

[3246, 326, 2754, 2547, 2457, 3456]

In [4]:
#Convert the list battle_deaths into a numpy array

deaths = np.array(battle_deaths)
deaths

array([3246,  326, 2754, 2547, 2457, 3456])

In [5]:
#Create an array of zeroes

defectors = np.zeros(6)
defectors

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
#Create a range from 0 to 100

zero_to_99 = np.arange(0,100)
zero_to_99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
#Create 100 ticks between 0 and 1

zero_to_1 = np.linspace(0,1)
zero_to_1

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])