**Imputing Missing class labels using K-Nearest Neighbors**

**Preliminaries**

In [1]:
#Load libraries

import numpy as np
from sklearn.neighbors import KNeighborsClassifier

**Create Feature Matrix**

In [2]:
#Create Feature Matrix with categorical variables

X = np.array([[0, 2.10, 1.45],
              [1, 1.18, 1.33],
              [0, 1.22, 1.27],
              [1, -0.21, -1.19]])
X

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

**Create Feature Matrix with missing values**

In [3]:
# Create feature matrix with missing values in the categorical feature
X_with_nan = np.array([[np.nan, 0.87, 1.31], 
                       [np.nan, -0.67, -0.22]])

**Train K Nearest Neighbor classifier**

In [4]:
#Train KNN Learner

clf = KNeighborsClassifier(n_neighbors=3,weights='distance')
trained_model = clf.fit(X[:,1:], X[:,0])

**Predict missing values' class**

In [10]:
#Predict missing values' class
imputed_values = trained_model.predict(X_with_nan[:,1:])
print(imputed_values.shape)
print(imputed_values)
print(imputed_values.reshape(-1,1))
#Join column of predicted class with their other features
X_with_imputed = np.hstack((imputed_values.reshape(-1,1),X_with_nan[:,1:]))

#Join two features matrices
np.vstack((X_with_imputed,X))

(2,)
[ 0.  1.]
[[ 0.]
 [ 1.]]


array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])